version: '3.4'
services:
  crystal:
    build: .
    command: tail -f /dev/null
    user: "${UID}"
    volumes:
      - .:/v
    working_dir: /v
    environment:
      PG_URL: 'postgres://user:pon@pg:5432/test'
      MYSQL_URL: 'mysql://user:pon@my:3306/test'
      SQLITE_URL: 'sqlite3:/tmp/test.db'
    depends_on:
      - pg
      - my

  pg:
    image: postgres:12.4
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB:       test
      POSTGRES_USER:     user
      POSTGRES_PASSWORD: pon

  my:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE:      test
      MYSQL_USER:          user
      MYSQL_PASSWORD:      pon
